package mapping;
// Generated 25-Jun-2013 13:27:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private Agent agent;
     private String balance;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Account() {
    }

	
    public Account(Agent agent) {
        this.agent = agent;
    }
    public Account(Agent agent, String balance, Set<Invoice> invoices) {
       this.agent = agent;
       this.balance = balance;
       this.invoices = invoices;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public String getBalance() {
        return this.balance;
    }
    
    public void setBalance(String balance) {
        this.balance = balance;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


