package mapping;
// Generated 25-Jun-2013 12:48:59 by Hibernate Tools 3.2.1.GA



/**
 * Agenthas generated by hbm2java
 */
public class Agenthas  implements java.io.Serializable {


     private Integer id;
     private Magazine magazine;
     private Agent agent;
     private String qty;

    public Agenthas() {
    }

	
    public Agenthas(Magazine magazine, Agent agent) {
        this.magazine = magazine;
        this.agent = agent;
    }
    public Agenthas(Magazine magazine, Agent agent, String qty) {
       this.magazine = magazine;
       this.agent = agent;
       this.qty = qty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Magazine getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(Magazine magazine) {
        this.magazine = magazine;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }




}


