package mapping;
// Generated 25-Jun-2013 09:57:44 by Hibernate Tools 3.2.1.GA



/**
 * Delibook generated by hbm2java
 */
public class Delibook  implements java.io.Serializable {


     private Integer id;
     private Route route;
     private Integer start;
     private Integer end;
     private String remarks;

    public Delibook() {
    }

	
    public Delibook(Route route) {
        this.route = route;
    }
    public Delibook(Route route, Integer start, Integer end, String remarks) {
       this.route = route;
       this.start = start;
       this.end = end;
       this.remarks = remarks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public Integer getStart() {
        return this.start;
    }
    
    public void setStart(Integer start) {
        this.start = start;
    }
    public Integer getEnd() {
        return this.end;
    }
    
    public void setEnd(Integer end) {
        this.end = end;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


