package mapping;
// Generated 25-Jun-2013 12:48:59 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deliver generated by hbm2java
 */
public class Deliver  implements java.io.Serializable {


     private Integer id;
     private Route route;
     private Magazine magazine;
     private Agent agent;
     private String deliId;
     private Date date;
     private String qty;
     private String rate;
     private String value;
     private Set personals = new HashSet(0);
     private Set stockdelis = new HashSet(0);

    public Deliver() {
    }

	
    public Deliver(Route route, Magazine magazine, Agent agent) {
        this.route = route;
        this.magazine = magazine;
        this.agent = agent;
    }
    public Deliver(Route route, Magazine magazine, Agent agent, String deliId, Date date, String qty, String rate, String value, Set personals, Set stockdelis) {
       this.route = route;
       this.magazine = magazine;
       this.agent = agent;
       this.deliId = deliId;
       this.date = date;
       this.qty = qty;
       this.rate = rate;
       this.value = value;
       this.personals = personals;
       this.stockdelis = stockdelis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public Magazine getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(Magazine magazine) {
        this.magazine = magazine;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public String getDeliId() {
        return this.deliId;
    }
    
    public void setDeliId(String deliId) {
        this.deliId = deliId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getStockdelis() {
        return this.stockdelis;
    }
    
    public void setStockdelis(Set stockdelis) {
        this.stockdelis = stockdelis;
    }




}


