package mapping;
// Generated 25-Jun-2013 12:48:59 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
public class District  implements java.io.Serializable {


     private Integer id;
     private String disName;
     private String disCode;
     private Set agents = new HashSet(0);

    public District() {
    }

    public District(String disName, String disCode, Set agents) {
       this.disName = disName;
       this.disCode = disCode;
       this.agents = agents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDisName() {
        return this.disName;
    }
    
    public void setDisName(String disName) {
        this.disName = disName;
    }
    public String getDisCode() {
        return this.disCode;
    }
    
    public void setDisCode(String disCode) {
        this.disCode = disCode;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }




}


