package mapping;
// Generated 25-Jun-2013 12:48:59 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Magazine generated by hbm2java
 */
public class Magazine  implements java.io.Serializable {


     private Integer id;
     private String magId;
     private String date;
     private String price;
     private String qty;
     private String totalCost;
     private String perMagCost;
     private String remarks;
     private Set stockdelis = new HashSet(0);
     private Set delivers = new HashSet(0);
     private Set agenthases = new HashSet(0);
     private Set personals = new HashSet(0);
     private Set rtns = new HashSet(0);
     private Set magexpences = new HashSet(0);
     private Set stocks = new HashSet(0);

    public Magazine() {
    }

    public Magazine(String magId, String date, String price, String qty, String totalCost, String perMagCost, String remarks, Set stockdelis, Set delivers, Set agenthases, Set personals, Set rtns, Set magexpences, Set stocks) {
       this.magId = magId;
       this.date = date;
       this.price = price;
       this.qty = qty;
       this.totalCost = totalCost;
       this.perMagCost = perMagCost;
       this.remarks = remarks;
       this.stockdelis = stockdelis;
       this.delivers = delivers;
       this.agenthases = agenthases;
       this.personals = personals;
       this.rtns = rtns;
       this.magexpences = magexpences;
       this.stocks = stocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMagId() {
        return this.magId;
    }
    
    public void setMagId(String magId) {
        this.magId = magId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(String totalCost) {
        this.totalCost = totalCost;
    }
    public String getPerMagCost() {
        return this.perMagCost;
    }
    
    public void setPerMagCost(String perMagCost) {
        this.perMagCost = perMagCost;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getStockdelis() {
        return this.stockdelis;
    }
    
    public void setStockdelis(Set stockdelis) {
        this.stockdelis = stockdelis;
    }
    public Set getDelivers() {
        return this.delivers;
    }
    
    public void setDelivers(Set delivers) {
        this.delivers = delivers;
    }
    public Set getAgenthases() {
        return this.agenthases;
    }
    
    public void setAgenthases(Set agenthases) {
        this.agenthases = agenthases;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getRtns() {
        return this.rtns;
    }
    
    public void setRtns(Set rtns) {
        this.rtns = rtns;
    }
    public Set getMagexpences() {
        return this.magexpences;
    }
    
    public void setMagexpences(Set magexpences) {
        this.magexpences = magexpences;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


