package mapping;
// Generated 25-Jun-2013 13:27:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Magazine generated by hbm2java
 */
public class Magazine  implements java.io.Serializable {


     private Integer id;
     private String magId;
     private String date;
     private String price;
     private String qty;
     private String totalCost;
     private String perMagCost;
     private String remarks;
     private Set<Stockdeli> stockdelis = new HashSet<Stockdeli>(0);
     private Set<Deliver> delivers = new HashSet<Deliver>(0);
     private Set<Agenthas> agenthases = new HashSet<Agenthas>(0);
     private Set<Personal> personals = new HashSet<Personal>(0);
     private Set<Rtn> rtns = new HashSet<Rtn>(0);
     private Set<Magexpence> magexpences = new HashSet<Magexpence>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Magazine() {
    }

    public Magazine(String magId, String date, String price, String qty, String totalCost, String perMagCost, String remarks, Set<Stockdeli> stockdelis, Set<Deliver> delivers, Set<Agenthas> agenthases, Set<Personal> personals, Set<Rtn> rtns, Set<Magexpence> magexpences, Set<Stock> stocks) {
       this.magId = magId;
       this.date = date;
       this.price = price;
       this.qty = qty;
       this.totalCost = totalCost;
       this.perMagCost = perMagCost;
       this.remarks = remarks;
       this.stockdelis = stockdelis;
       this.delivers = delivers;
       this.agenthases = agenthases;
       this.personals = personals;
       this.rtns = rtns;
       this.magexpences = magexpences;
       this.stocks = stocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMagId() {
        return this.magId;
    }
    
    public void setMagId(String magId) {
        this.magId = magId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(String totalCost) {
        this.totalCost = totalCost;
    }
    public String getPerMagCost() {
        return this.perMagCost;
    }
    
    public void setPerMagCost(String perMagCost) {
        this.perMagCost = perMagCost;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set<Stockdeli> getStockdelis() {
        return this.stockdelis;
    }
    
    public void setStockdelis(Set<Stockdeli> stockdelis) {
        this.stockdelis = stockdelis;
    }
    public Set<Deliver> getDelivers() {
        return this.delivers;
    }
    
    public void setDelivers(Set<Deliver> delivers) {
        this.delivers = delivers;
    }
    public Set<Agenthas> getAgenthases() {
        return this.agenthases;
    }
    
    public void setAgenthases(Set<Agenthas> agenthases) {
        this.agenthases = agenthases;
    }
    public Set<Personal> getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set<Personal> personals) {
        this.personals = personals;
    }
    public Set<Rtn> getRtns() {
        return this.rtns;
    }
    
    public void setRtns(Set<Rtn> rtns) {
        this.rtns = rtns;
    }
    public Set<Magexpence> getMagexpences() {
        return this.magexpences;
    }
    
    public void setMagexpences(Set<Magexpence> magexpences) {
        this.magexpences = magexpences;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


