package mapping;
// Generated 25-Jun-2013 09:57:44 by Hibernate Tools 3.2.1.GA



/**
 * Magexpence generated by hbm2java
 */
public class Magexpence  implements java.io.Serializable {


     private Integer id;
     private Magazine magazine;
     private String type;
     private String value;

    public Magexpence() {
    }

	
    public Magexpence(Magazine magazine) {
        this.magazine = magazine;
    }
    public Magexpence(Magazine magazine, String type, String value) {
       this.magazine = magazine;
       this.type = type;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Magazine getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(Magazine magazine) {
        this.magazine = magazine;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


