package mapping;
// Generated 25-Jun-2013 13:27:56 by Hibernate Tools 3.2.1.GA



/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer id;
     private Rtn rtn;
     private Deliver deliver;
     private Magazine magazine;
     private Invoice invoice;
     private Agent agent;
     private String letter;
     private String totalQty;
     private String credit;
     private String debit;
     private String totalBal;
     private String status;
     private Byte complete;

    public Personal() {
    }

	
    public Personal(Magazine magazine, Agent agent) {
        this.magazine = magazine;
        this.agent = agent;
    }
    public Personal(Rtn rtn, Deliver deliver, Magazine magazine, Invoice invoice, Agent agent, String letter, String totalQty, String credit, String debit, String totalBal, String status, Byte complete) {
       this.rtn = rtn;
       this.deliver = deliver;
       this.magazine = magazine;
       this.invoice = invoice;
       this.agent = agent;
       this.letter = letter;
       this.totalQty = totalQty;
       this.credit = credit;
       this.debit = debit;
       this.totalBal = totalBal;
       this.status = status;
       this.complete = complete;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rtn getRtn() {
        return this.rtn;
    }
    
    public void setRtn(Rtn rtn) {
        this.rtn = rtn;
    }
    public Deliver getDeliver() {
        return this.deliver;
    }
    
    public void setDeliver(Deliver deliver) {
        this.deliver = deliver;
    }
    public Magazine getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(Magazine magazine) {
        this.magazine = magazine;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public String getLetter() {
        return this.letter;
    }
    
    public void setLetter(String letter) {
        this.letter = letter;
    }
    public String getTotalQty() {
        return this.totalQty;
    }
    
    public void setTotalQty(String totalQty) {
        this.totalQty = totalQty;
    }
    public String getCredit() {
        return this.credit;
    }
    
    public void setCredit(String credit) {
        this.credit = credit;
    }
    public String getDebit() {
        return this.debit;
    }
    
    public void setDebit(String debit) {
        this.debit = debit;
    }
    public String getTotalBal() {
        return this.totalBal;
    }
    
    public void setTotalBal(String totalBal) {
        this.totalBal = totalBal;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Byte getComplete() {
        return this.complete;
    }
    
    public void setComplete(Byte complete) {
        this.complete = complete;
    }




}


