package mapping;
// Generated 25-Jun-2013 12:48:59 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String code;
     private Set invbooks = new HashSet(0);
     private Set delibooks = new HashSet(0);
     private Set rtns = new HashSet(0);
     private Set delivers = new HashSet(0);
     private Set agents = new HashSet(0);
     private Set rtnbooks = new HashSet(0);

    public Route() {
    }

    public Route(String name, String code, Set invbooks, Set delibooks, Set rtns, Set delivers, Set agents, Set rtnbooks) {
       this.name = name;
       this.code = code;
       this.invbooks = invbooks;
       this.delibooks = delibooks;
       this.rtns = rtns;
       this.delivers = delivers;
       this.agents = agents;
       this.rtnbooks = rtnbooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getInvbooks() {
        return this.invbooks;
    }
    
    public void setInvbooks(Set invbooks) {
        this.invbooks = invbooks;
    }
    public Set getDelibooks() {
        return this.delibooks;
    }
    
    public void setDelibooks(Set delibooks) {
        this.delibooks = delibooks;
    }
    public Set getRtns() {
        return this.rtns;
    }
    
    public void setRtns(Set rtns) {
        this.rtns = rtns;
    }
    public Set getDelivers() {
        return this.delivers;
    }
    
    public void setDelivers(Set delivers) {
        this.delivers = delivers;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }
    public Set getRtnbooks() {
        return this.rtnbooks;
    }
    
    public void setRtnbooks(Set rtnbooks) {
        this.rtnbooks = rtnbooks;
    }




}


