package mapping;
// Generated 25-Jun-2013 12:48:59 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Stockdeli generated by hbm2java
 */
public class Stockdeli  implements java.io.Serializable {


     private Integer id;
     private Deliver deliver;
     private Magazine magazine;
     private Date date;
     private String qty;

    public Stockdeli() {
    }

	
    public Stockdeli(Deliver deliver, Magazine magazine) {
        this.deliver = deliver;
        this.magazine = magazine;
    }
    public Stockdeli(Deliver deliver, Magazine magazine, Date date, String qty) {
       this.deliver = deliver;
       this.magazine = magazine;
       this.date = date;
       this.qty = qty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Deliver getDeliver() {
        return this.deliver;
    }
    
    public void setDeliver(Deliver deliver) {
        this.deliver = deliver;
    }
    public Magazine getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(Magazine magazine) {
        this.magazine = magazine;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }




}


