package mapping;
// Generated 25-Jun-2013 09:57:44 by Hibernate Tools 3.2.1.GA



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer id;
     private String supId;
     private String supName;
     private String phone;
     private String remarks;

    public Supplier() {
    }

    public Supplier(String supId, String supName, String phone, String remarks) {
       this.supId = supId;
       this.supName = supName;
       this.phone = phone;
       this.remarks = remarks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSupId() {
        return this.supId;
    }
    
    public void setSupId(String supId) {
        this.supId = supId;
    }
    public String getSupName() {
        return this.supName;
    }
    
    public void setSupName(String supName) {
        this.supName = supName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


