package mapping;
// Generated 25-Jun-2013 09:57:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userlog generated by hbm2java
 */
public class Userlog  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date date;
     private String activity;

    public Userlog() {
    }

	
    public Userlog(User user) {
        this.user = user;
    }
    public Userlog(User user, Date date, String activity) {
       this.user = user;
       this.date = date;
       this.activity = activity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }




}


