package model;
// Generated 21-Jun-2013 11:23:58 by Hibernate Tools 3.2.1.GA



/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String des;

    public Log() {
    }

	
    public Log(User user) {
        this.user = user;
    }
    public Log(User user, String des) {
       this.user = user;
       this.des = des;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }




}


